name: CI/CD
on:
  push:
    branches: [ master ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # - name: Run Tests
      #   run: |
      #     python -m unittest discover -s src/tests/
  deployment:
    needs: test_suite
    runs-on: ubuntu-latest
    steps:
      - name: Fresh clone & repo install
        uses: appleboy/ssh-action@master
        with:
          #IP address of EC2 instance
          host: 50.17.74.153
          #User you created on the EC2 instance
          username: ubuntu
          #Name of the secrets variable where you put your secret key
          key: ${{ 'SSH_KEY' }}
          port: 22
          script: |
            git clone https://github.com/seanremenyi/Flight-Search.git
          # python3.8 -m venv /home/ubuntu/SeanRemenyi_T2A3/venv
          # /home/github-actions/SeanRemenyi_T2A3/venv/bin/pip3.8 install -r /home/github-actions/squiz/requirements.txt