name: CI/CD
on:
  push:
    branches: [ master ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Tests
        run: |
          cd src
          python -m unittest discover -s tests/
  deployment:
    needs: test_suite
    runs-on: ubuntu-latest
    steps:
      - name: Fresh clone & repo install
        uses: appleboy/ssh-action@master
        with:
          host: 50.17.74.153
          username: flight
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            rm -rf Flight-Search
            git clone https://github.com/seanremenyi/Flight-Search.git
            python3.8 -m venv /home/flight/Flight-Search/venv
            /home/flight/Flight-Search/venv/bin/pip install -r Flight-Search/requirements.txt